name: Auto merge pull requests
on:
  check_suite:
    types: [completed]
    branches: [develop, master]
jobs:
  build:
    name: AutoMergePR
    # This job runs on github hosted Linux machine
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Test user'
        id: hello
      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
